### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by mosrainis** [mosrainis/SHBHiking#1]
- [x] Redesign the website with Vue.js
- [x] Redesign the responsive system
- [ ] Develop the content section
- [ ] Develop the back-end of SHB Hiking with PHP language. It need to be compatible with WordPress
### Optional :
- [ ] Convert the project to the EN version
- [ ] New features (Like tools that improves user experience)
